"""initial schema

Revision ID: 5666ba96e8db
Revises: 
Create Date: 2026-06-07 08:37:12.364591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5666ba96e8db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('idea', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('visual_style', sa.String(), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('video_backend', sa.String(), nullable=False),
    sa.Column('transition', sa.String(), nullable=False),
    sa.Column('transition_duration', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('audio',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('beats', sa.JSON(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('waveform', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('face', sa.String(), nullable=False),
    sa.Column('hair', sa.String(), nullable=False),
    sa.Column('clothing', sa.String(), nullable=False),
    sa.Column('personality', sa.String(), nullable=False),
    sa.Column('identity_anchors', sa.JSON(), nullable=False),
    sa.Column('ref_image_path', sa.String(), nullable=True),
    sa.Column('ref_status', sa.String(), nullable=False),
    sa.Column('lora_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_project_id'), ['project_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('result_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)

    op.create_table('lyrics',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('music_prompt', sa.String(), nullable=False),
    sa.Column('emotional_arc', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('visual_description', sa.String(), nullable=False),
    sa.Column('camera_instruction', sa.String(), nullable=False),
    sa.Column('motion_instruction', sa.String(), nullable=False),
    sa.Column('keyframe_prompt', sa.String(), nullable=False),
    sa.Column('video_prompt', sa.String(), nullable=False),
    sa.Column('negative_prompt', sa.String(), nullable=False),
    sa.Column('keyframe_path', sa.String(), nullable=True),
    sa.Column('keyframe_status', sa.String(), nullable=False),
    sa.Column('keyframe_prompt_version', sa.Integer(), nullable=True),
    sa.Column('clip_path', sa.String(), nullable=True),
    sa.Column('clip_status', sa.String(), nullable=False),
    sa.Column('clip_prompt_version', sa.Integer(), nullable=True),
    sa.Column('video_backend_override', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_project_id'), ['project_id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('keyframe_prompt', sa.String(), nullable=False),
    sa.Column('video_prompt', sa.String(), nullable=False),
    sa.Column('negative_prompt', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_scene_id'), ['scene_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_scene_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_project_id'))

    op.drop_table('scenes')
    op.drop_table('lyrics')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_project_id'))

    op.drop_table('characters')
    op.drop_table('audio')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
